language: php
php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: hhvm
    - php: nightly

script:
  - ./tests/run.sh

install:
  - composer install --dev

before_install:
  - composer self-update
