language: php

php:
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly

matrix:
  allow_failures:
    - php: nightly

script:
  - composer run-script phpcs
  - ./tests/run.sh

install:
  - composer install --dev
